#!/bin/sh
#require prefix
#require make
#phase makefile
dispn "Writing Makefile top entries..."
if test "$MAKE_CONDSET" = "y"; then
	$ECHO "PREFIX ?= $FM_PREFIX"

	if test "$FM_MANDIRSTRICT" = "y"; then
		$ECHO "MANDIR ?= $FM_MANDIR"
	else
		$ECHO "MANDIR ?= \$(PREFIX)/man"
	fi

	if test "$FM_CONFDIRSTRICT" = "y"; then
		$ECHO "CONFDIR ?= $FM_CONFDIR"
	else
		$ECHO "CONFDIR ?= \$(PREFIX)/etc"
	fi

	if test "$FM_BINDIRSTRICT" = "y"; then
		$ECHO "BINDIR ?= $FM_BINDIR"
	else
		$ECHO "BINDIR ?= \$(PREFIX)/bin"
	fi

	if test "$FM_SBINDIRSTRICT" = "y"; then
		$ECHO "SBINDIR ?= $FM_SBINDIR"
	else
		$ECHO "SBINDIR ?= \$(PREFIX)/sbin"
	fi

	if test "$FM_LIBDIRSTRICT" = "y"; then
		$ECHO "LIBDIR ?= $FM_LIBDIR"
	else
		$ECHO "LIBDIR ?= \$(PREFIX)/lib"
	fi

	if test "$FM_INCLUDEDIRSTRICT" = "y"; then
		$ECHO "INCLUDEDIR ?= $FM_INCLUDEDIR"
	else
		$ECHO "INCLUDEDIR ?= \$(PREFIX)/include"
	fi
else
	$ECHO "PREFIX = $FM_PREFIX"
	$ECHO "MANDIR = $FM_MANDIR"
	$ECHO "CONFDIR = $FM_CONFDIR"
	$ECHO "BINDIR = $FM_BINDIR"
	$ECHO "SBINDIR = $FM_SBINDIR"
	$ECHO "LIBDIR = $FM_LIBDIR"
	$ECHO "INCLUDEDIR = $FM_INCLUDEDIR"
fi
$ECHO
$ECHO "all:"
$ECHO -n "$MAKEFILE_ALL"
$ECHO


$ECHO ".c.o:"
$ECHO "	$CC $FM_CFLAGS -DCONFDIR=\"\\\"\$(CONFDIR)\\\"\" -DBINDIR=\"\\\"\$(BINDIR)\\\"\" -DSBINDIR=\"\\\"\$(SBINDIR)\\\"\" -DLIBDIR=\"\\\"\$(LIBDIR)\\\"\" -DMANDIR=\"\\\"\$(MANDIR)\\\"\" -c -o \$@ \$<"
$ECHO


$ECHO "clean:"
$ECHO -n "$MAKEFILE_CLEAN"
$ECHO


$ECHO "distclean:"
$ECHO "	\$(MAKE) clean"
$ECHO -n "$MAKEFILE_DISTCLEAN"
$ECHO "	rm -f Makefile firemake.h"
$ECHO

disp "done"
